package com.yory3r.e_learning.model;

import java.util.ArrayList;

public class LordsMobileDummy
{
    public ArrayList<LordsMobile> listLordsMobile;
    public LordsMobileDummy()
    {
        listLordsMobile = new ArrayList<>();
        listLordsMobile.add(hero1);
        listLordsMobile.add(hero2);
        listLordsMobile.add(hero3);
        listLordsMobile.add(hero4);
        listLordsMobile.add(hero5);
        listLordsMobile.add(hero6);
        listLordsMobile.add(hero7);
        listLordsMobile.add(hero8);
        listLordsMobile.add(hero9);
        listLordsMobile.add(hero10);
        listLordsMobile.add(hero11);
        listLordsMobile.add(hero12);
        listLordsMobile.add(hero13);
        listLordsMobile.add(hero14);
        listLordsMobile.add(hero15);
        listLordsMobile.add(hero16);
        listLordsMobile.add(hero17);
        listLordsMobile.add(hero18);
        listLordsMobile.add(hero19);
        listLordsMobile.add(hero20);
        listLordsMobile.add(hero21);
        listLordsMobile.add(hero22);
        listLordsMobile.add(hero23);
        listLordsMobile.add(hero24);
        listLordsMobile.add(hero25);
        listLordsMobile.add(hero26);
        listLordsMobile.add(hero27);
        listLordsMobile.add(hero28);
        listLordsMobile.add(hero29);
        listLordsMobile.add(hero30);
        listLordsMobile.add(hero31);
        listLordsMobile.add(hero32);
        listLordsMobile.add(hero33);
        listLordsMobile.add(hero34);
        listLordsMobile.add(hero35);
        listLordsMobile.add(hero36);
        listLordsMobile.add(hero37);
        listLordsMobile.add(hero38);
        listLordsMobile.add(hero39);
        listLordsMobile.add(hero40);
        listLordsMobile.add(hero41);
        listLordsMobile.add(hero42);
        listLordsMobile.add(hero43);
        listLordsMobile.add(hero44);
        listLordsMobile.add(hero45);
        listLordsMobile.add(hero46);
        listLordsMobile.add(hero47);
        listLordsMobile.add(hero48);
        listLordsMobile.add(hero49);
        listLordsMobile.add(hero50);
        listLordsMobile.add(hero51);
        listLordsMobile.add(hero52);
    }

    public static final LordsMobile hero1 = new LordsMobile("Boommeister","https://static.wikia.nocookie.net/lordsmobile/images/a/a2/Boommeister.png/revision/latest/scale-to-width-down/350?cb=20200308165732");
    public static final LordsMobile hero2 = new LordsMobile("Chaos Dragon", "https://static.wikia.nocookie.net/lordsmobile/images/a/af/Chaos_Dragon.png/revision/latest/scale-to-width-down/350?cb=20200308165738");
    public static final LordsMobile hero3 = new LordsMobile("Watcher", "https://static.wikia.nocookie.net/lordsmobile/images/9/98/Watcher.png/revision/latest/scale-to-width-down/350?cb=20200308171321");
    public static final LordsMobile hero4 = new LordsMobile("Pegasus", "https://static.wikia.nocookie.net/lordsmobile/images/4/4a/Pegasus.png/revision/latest/scale-to-width-down/236?cb=20210402103246");
    public static final LordsMobile hero5 = new LordsMobile("Black Crow", "https://static.wikia.nocookie.net/lordsmobile/images/2/24/Black_Crow.png/revision/latest/scale-to-width-down/350?cb=20200308042542");
    public static final LordsMobile hero6 = new LordsMobile("Bombin' Goblin", "https://static.wikia.nocookie.net/lordsmobile/images/b/b1/Bombin%27_Goblin.png/revision/latest/scale-to-width-down/350?cb=20200308045025");
    public static final LordsMobile hero7 = new LordsMobile("Child of Light", "https://static.wikia.nocookie.net/lordsmobile/images/e/e2/Child_of_Light.png/revision/latest/scale-to-width-down/350?cb=20200308165745");
    public static final LordsMobile hero8 = new LordsMobile("Death Archer", "https://static.wikia.nocookie.net/lordsmobile/images/0/0c/Death_Archer.png/revision/latest/scale-to-width-down/350?cb=20200308043403");
    public static final LordsMobile hero9 = new LordsMobile("Death Knight", "https://static.wikia.nocookie.net/lordsmobile/images/3/32/Death_Knight.png/revision/latest/scale-to-width-down/350?cb=20200308165754");
    public static final LordsMobile hero10 = new LordsMobile("Demon Slayer", "https://static.wikia.nocookie.net/lordsmobile/images/a/ac/Demon_Slayer.png/revision/latest/scale-to-width-down/350?cb=20200308165801");
    public static final LordsMobile hero11 = new LordsMobile("Elementalist", "https://static.wikia.nocookie.net/lordsmobile/images/a/a6/Elementalist.png/revision/latest/scale-to-width-down/350?cb=20200308165805");
    public static final LordsMobile hero12 = new LordsMobile("Incinerator", "https://static.wikia.nocookie.net/lordsmobile/images/5/5b/Incinerator.png/revision/latest/scale-to-width-down/350?cb=20200308045353");
    public static final LordsMobile hero13 = new LordsMobile("Night Raven", "https://static.wikia.nocookie.net/lordsmobile/images/2/21/Night_Raven.png/revision/latest/scale-to-width-down/350?cb=20200308165847");
    public static final LordsMobile hero14 = new LordsMobile("Oath Keeper", "https://static.wikia.nocookie.net/lordsmobile/images/4/48/Oath_Keeper.png/revision/latest/scale-to-width-down/350?cb=20200308165853");
    public static final LordsMobile hero15 = new LordsMobile("Prima Donna", "https://static.wikia.nocookie.net/lordsmobile/images/f/fa/Prima_Donna.png/revision/latest/scale-to-width-down/350?cb=20200308050501");
    public static final LordsMobile hero16 = new LordsMobile("Rose Knight", "https://static.wikia.nocookie.net/lordsmobile/images/5/54/Rose_Knight.png/revision/latest/scale-to-width-down/350?cb=20200308171157");
    public static final LordsMobile hero17 = new LordsMobile("Scarlet Bolt", "https://static.wikia.nocookie.net/lordsmobile/images/c/c1/Scarlet_Bolt.png/revision/latest/scale-to-width-down/350?cb=20200308044835");
    public static final LordsMobile hero18 = new LordsMobile("Sage of Storms", "https://static.wikia.nocookie.net/lordsmobile/images/3/31/Sage_of_Storms.png/revision/latest/scale-to-width-down/350?cb=20200308171207");
    public static final LordsMobile hero19 = new LordsMobile("Sea Squire", "https://static.wikia.nocookie.net/lordsmobile/images/1/1e/Sea_Squire.png/revision/latest/scale-to-width-down/350?cb=20200308051128");
    public static final LordsMobile hero20 = new LordsMobile("Snow Queen", "https://static.wikia.nocookie.net/lordsmobile/images/7/7a/Snow_Queen.png/revision/latest/scale-to-width-down/350?cb=20200308171234");
    public static final LordsMobile hero21 = new LordsMobile("Shade", "https://static.wikia.nocookie.net/lordsmobile/images/d/dc/Shade.png/revision/latest/scale-to-width-down/350?cb=20200308171214");
    public static final LordsMobile hero22 = new LordsMobile("Soul Forger", "https://static.wikia.nocookie.net/lordsmobile/images/8/82/Soul_Forger.png/revision/latest/scale-to-width-down/350?cb=20200308171243");
    public static final LordsMobile hero23 = new LordsMobile("Trickster", "https://static.wikia.nocookie.net/lordsmobile/images/b/bd/Trickster.png/revision/latest/scale-to-width-down/350?cb=20200308051433");
    public static final LordsMobile hero24 = new LordsMobile("Tracker", "https://static.wikia.nocookie.net/lordsmobile/images/c/c5/Tracker.png/revision/latest/scale-to-width-down/350?cb=20200308044508");
    public static final LordsMobile hero25 = new LordsMobile("Barbarian", "https://static.wikia.nocookie.net/lordsmobile/images/b/b6/Barbarian.png/revision/latest/scale-to-width-down/350?cb=20200308165726");
    public static final LordsMobile hero26 = new LordsMobile("Berserker", "https://static.wikia.nocookie.net/lordsmobile/images/a/a8/Berserker.png/revision/latest/scale-to-width-down/350?cb=20191023164835");
    public static final LordsMobile hero27 = new LordsMobile("Chronicler", "https://static.wikia.nocookie.net/lordsmobile/images/f/f9/Chronicler.png/revision/latest/scale-to-width-down/279?cb=20201017223919");
    public static final LordsMobile hero28 = new LordsMobile("Cursed Hunter", "https://static.wikia.nocookie.net/lordsmobile/images/e/ee/Cursed_Hunter.png/revision/latest/scale-to-width-down/350?cb=20190614190942");
    public static final LordsMobile hero29 = new LordsMobile("Dark Follower", "https://static.wikia.nocookie.net/lordsmobile/images/8/8d/Dark_Follower.png/revision/latest/scale-to-width-down/350?cb=20200308165750");
    public static final LordsMobile hero30 = new LordsMobile("Dark Magister", "https://static.wikia.nocookie.net/lordsmobile/images/d/d2/Dark_Magister.png/revision/latest/scale-to-width-down/350?cb=20191023164953");
    public static final LordsMobile hero31 = new LordsMobile("Dream Witch", "https://static.wikia.nocookie.net/lordsmobile/images/2/26/Dream_Witch.png/revision/latest/scale-to-width-down/350?cb=20200308045618");
    public static final LordsMobile hero32 = new LordsMobile("Don Guapo", "https://static.wikia.nocookie.net/lordsmobile/images/0/01/Don_Guapo.png/revision/latest/scale-to-width-down/350?cb=20200308050308");
    public static final LordsMobile hero33 = new LordsMobile("Ethereal Guide", "https://static.wikia.nocookie.net/lordsmobile/images/4/44/Ethereal_Guide.png/revision/latest/scale-to-width-down/350?cb=20200115223558");
    public static final LordsMobile hero34 = new LordsMobile("Femme Fatale", "https://static.wikia.nocookie.net/lordsmobile/images/3/33/Femme_Fatale.png/revision/latest/scale-to-width-down/350?cb=20200308165812");
    public static final LordsMobile hero35 = new LordsMobile("Grim Wolf", "https://static.wikia.nocookie.net/lordsmobile/images/f/f4/Grim_Wolf.png/revision/latest/scale-to-width-down/350?cb=20200308165818");
    public static final LordsMobile hero36 = new LordsMobile("Grove Guardian", "https://static.wikia.nocookie.net/lordsmobile/images/d/d2/Grove_Guardian.png/revision/latest/scale-to-width-down/350?cb=20200308165824");
    public static final LordsMobile hero37 = new LordsMobile("Lightweaver", "https://static.wikia.nocookie.net/lordsmobile/images/d/d1/Lightweaver.png/revision/latest/scale-to-width-down/350?cb=20200308165830");
    public static final LordsMobile hero38 = new LordsMobile("Lore Weaver", "https://static.wikia.nocookie.net/lordsmobile/images/1/12/Lore_Weaver.png/revision/latest/scale-to-width-down/350?cb=20200308165835");
    public static final LordsMobile hero39 = new LordsMobile("Magmaroid", "https://static.wikia.nocookie.net/lordsmobile/images/b/be/Magmaroid.png/revision/latest/scale-to-width-down/350?cb=20200604120712");
    public static final LordsMobile hero40 = new LordsMobile("Mastercook", "https://static.wikia.nocookie.net/lordsmobile/images/6/66/Mastercook.png/revision/latest/scale-to-width-down/350?cb=20200308165842");
    public static final LordsMobile hero41 = new LordsMobile("Necroduke", "");
    public static final LordsMobile hero42 = new LordsMobile("Petite Devil", "https://static.wikia.nocookie.net/lordsmobile/images/9/9e/Petite_Devil.png/revision/latest/scale-to-width-down/350?cb=20200308045810");
    public static final LordsMobile hero43 = new LordsMobile("Prince of Thieves", "https://static.wikia.nocookie.net/lordsmobile/images/d/d6/Prince_of_Thieves.png/revision/latest/scale-to-width-down/350?cb=20200308171152");
    public static final LordsMobile hero44 = new LordsMobile("Shape Shifter", "https://static.wikia.nocookie.net/lordsmobile/images/f/f4/Shape_Shifter.png/revision/latest/scale-to-width-down/350?cb=20200308171221");
    public static final LordsMobile hero45 = new LordsMobile("Snail Princess", "https://static.wikia.nocookie.net/lordsmobile/images/5/56/Snail_Princess.png/revision/latest/scale-to-width-down/350?cb=20200308171228");
    public static final LordsMobile hero46 = new LordsMobile("Songstress of the Sea", "https://static.wikia.nocookie.net/lordsmobile/images/4/4f/Songstress_of_the_Sea.png/revision/latest/scale-to-width-down/350?cb=20190614181708");
    public static final LordsMobile hero47 = new LordsMobile("Steambot", "https://static.wikia.nocookie.net/lordsmobile/images/2/2c/Steambot.png/revision/latest/scale-to-width-down/350?cb=20200308171249");
    public static final LordsMobile hero48 = new LordsMobile("Storm Fox", "https://static.wikia.nocookie.net/lordsmobile/images/c/ca/Storm_Fox.png/revision/latest/scale-to-width-down/350?cb=20200308171254");
    public static final LordsMobile hero49 = new LordsMobile("The Big Guy", "https://static.wikia.nocookie.net/lordsmobile/images/b/b4/The_Big_Guy.png/revision/latest/scale-to-width-down/350?cb=20200308171300");
    public static final LordsMobile hero50 = new LordsMobile("Twilight Priestess", "https://static.wikia.nocookie.net/lordsmobile/images/8/88/Twilight_Priestess.png/revision/latest/scale-to-width-down/350?cb=20200308171309");
    public static final LordsMobile hero51 = new LordsMobile("Vengeful Centaur", "https://static.wikia.nocookie.net/lordsmobile/images/3/31/Vengeful_Centaur.png/revision/latest/scale-to-width-down/350?cb=20200308171315");
    public static final LordsMobile hero52 = new LordsMobile("Witch Doll", "https://static.wikia.nocookie.net/lordsmobile/images/7/7a/Witch_Doll.png/revision/latest/scale-to-width-down/350?cb=20200308050858");
}